/**
 * Schemas for the JSON files in src/data/.
 *
 * These are the contract between the site and the Python pipelines: the
 * pipelines overwrite these files with real data, so mock data must match
 * these shapes exactly.
 */

/** teams.json: one entry per team, generated by pipelines/build_teams.py. */
export interface Team {
  abbr: string;
  name: string;
  conference: 'AFC' | 'NFC';
  /** e.g. "AFC East" */
  division: string;
  /** Hex color, e.g. "#97233f" */
  primary: string;
  secondary: string;
}
export type TeamsData = Team[];

/** ticker.json: one full NFL week of games. */
export type GameState = 'pre' | 'live' | 'final';

export interface TickerGame {
  /** Stable id, e.g. "2026_02_DET_BUF" */
  id: string;
  /** Team abbr matching teams.json */
  away: string;
  home: string;
  /** null until kickoff */
  awayScore: number | null;
  homeScore: number | null;
  /**
   * Game status. The daily pipeline writes only "pre" and "final"; "live"
   * is reserved for runtime game state fetched in the browser.
   */
  state: GameState;
  /**
   * Display string: "Final", "Final/OT", "Sun 1:00 PM", "Sat TBD". Kickoff
   * times here are US Eastern; the browser replaces them with the visitor's
   * local time from `kickoff`.
   */
  detail: string;
  /** Kickoff in ISO 8601 UTC, e.g. "2026-09-18T00:15:00Z". Null until scheduled. */
  kickoff: string | null;
  /** ESPN event id recorded by nflverse, used to match live scores. Null if unknown. */
  espnId: string | null;
}

export interface TickerData {
  /** ISO timestamp of the last pipeline run */
  updated: string;
  season: number;
  /**
   * NFL week on display, chosen by pipelines/ticker.py when it runs: on
   * Tuesday the week that just ended, from Wednesday on the upcoming week.
   * Postseason weeks are 19 to 22. Null in the offseason.
   */
  week: number | null;
  /**
   * Offseason only (games empty): date of next season's opening game,
   * "YYYY-MM-DD". Null during the season.
   */
  nextOpener: string | null;
  games: TickerGame[];
}

/** on_this_day.json */
/** on_this_day.json: written daily by pipelines/on_this_day.py from nflverse schedules. */
export interface OnThisDayPart {
  text: string;
  /** Present when this part is a team name: the current team abbr to link to */
  team?: string;
}

export interface OnThisDayItem {
  year: number;
  /** nflverse game id */
  gameId: string;
  /** The whole sentence */
  text: string;
  /** The same sentence split so team names can be links */
  parts: OnThisDayPart[];
}

export interface OnThisDayData {
  month: number;
  day: number;
  /** Games played on this date since 1999; 0 means none at all, not none notable */
  gamesOnDate: number;
  /** Up to 3, one per season, newest first */
  items: OnThisDayItem[];
}

/** rosters/{ABBR}.json: one file per team, generated by pipelines/rosters.py. */
export type PositionGroup = 'offense' | 'defense' | 'specialists' | 'other';

export interface RosterPlayer {
  /** nflverse gsis id. Null for the occasional player without one. */
  gsisId: string | null;
  name: string;
  /**
   * URL slug, unique across the league. Players who share a name carry a
   * team suffix, so links must use this rather than deriving a slug.
   */
  slug: string;
  /** Jersey number, null when unassigned. */
  number: number | null;
  /** Specific position (CB, G, T), not the coarse group (DB, OL). */
  position: string;
  group: PositionGroup;
  /** Raw nflverse status code (ACT, RES, DEV, PUP, ...), per the nflverse roster status dictionary. */
  status: string;
  /** The code in words, e.g. "Practice squad". */
  statusLabel: string;
  /** Height in inches, null when nflverse has no listing. */
  heightInches: number | null;
  weight: number | null;
  /** Age on the day the pipeline ran. Null without a birth date. */
  age: number | null;
  /** Completed NFL seasons; 0 is a rookie. */
  experience: number;
  /** Semicolon separated when a player attended more than one. */
  college: string | null;
}

export interface TeamRoster {
  season: number;
  /** Team abbr matching teams.json */
  team: string;
  /** Week of the nflverse roster snapshot this came from. */
  week: number;
  /** ISO timestamp of the run that last changed this roster */
  updated: string;
  /** Position groups present on this roster, in display order. */
  groups: { key: PositionGroup; label: string }[];
  /** Sorted by group, then position, then jersey number. */
  players: RosterPlayer[];
}

/** team_stats.json: written weekly by pipelines/run_weekly.py from nflverse play-by-play. */
export type StatFormat = 'signed3' | 'percent1';

export interface TeamStatMetric {
  /** Stable key, e.g. "off_epa" */
  key: string;
  /** Full name, e.g. "Red zone TD rate allowed" */
  label: string;
  /** Column header, e.g. "Red zone TD" */
  short: string;
  side: 'offense' | 'defense';
  format: StatFormat;
  /** Rank 1 goes to the highest value, or the lowest for defense. */
  betterWhen: 'high' | 'low';
  /** What `n` counts: "plays", "attempts" or "trips". */
  sample: string;
  /** One sentence definition shown on the team stats page. */
  description: string;
}

export interface TeamStatValue {
  /** Rate or per play value; null when the team has no sample yet. */
  value: number | null;
  /** 1 to 32, ties shared; null when value is null. */
  rank: number | null;
  /** Plays, attempts or trips behind the value. */
  n: number;
}

export interface TeamStatLine {
  /** Team abbr matching teams.json */
  abbr: string;
  games: number;
  /** Keyed by TeamStatMetric.key */
  values: Record<string, TeamStatValue>;
}

export interface TeamStatsData {
  season: number;
  /** Last regular season week included, 0 before any games */
  throughWeek: number;
  /** ISO timestamp of the run that last changed the numbers */
  updated: string;
  metrics: TeamStatMetric[];
  teams: TeamStatLine[];
}

/** stats/{board}.json: full player leaderboards, written daily by pipelines/leaderboards.py. */
export type BoardFormat = 'integer' | 'decimal1' | 'percent1';

export interface BoardColumn {
  /** Key into BoardRow.values */
  key: string;
  /** Column header, e.g. "Y/A" */
  label: string;
  /** Full name, e.g. "Yards per carry" */
  title: string;
  format: BoardFormat;
  /** Counting stat that the per game view divides by games played. */
  perGame: boolean;
  /** A ratio of two other columns; sorting by it ranks qualified players only. */
  rate: boolean;
  /** Direction a first click sorts in, and which way rank 1 points. */
  better: 'high' | 'low';
}

export interface BoardRow {
  /** Rank by the board's primary column, totals, all players */
  rank: number;
  /** nflverse gsis id, matching RosterPlayer.gsisId */
  playerId: string;
  player: string;
  /** Team abbr matching teams.json */
  team: string;
  position: string | null;
  /** Games the player's current team has played */
  teamGames: number;
  /** Meets the board's qualifier */
  qualified: boolean;
  /** Keyed by BoardColumn.key; null where a rate has no denominator */
  values: Record<string, number | null>;
}

export interface LeaderboardData {
  /** URL key under /stats, e.g. "rushing" */
  key: string;
  label: string;
  season: number;
  throughWeek: number;
  /** Column the board ranks by by default */
  primary: string;
  qualifier: {
    /** Column the bar is measured in */
    column: string;
    perTeamGame: number;
    /** Sentence for the page, e.g. "At least 6 carries per team game." */
    text: string;
  };
  columns: BoardColumn[];
  /** Ranked by the primary column */
  rows: BoardRow[];
}

/** transactions.json: roster moves and the injury report, written daily by pipelines/transactions.py. */
export type MoveType = 'signed' | 'joined' | 'released' | 'retired' | 'left' | 'status';

/** Filter category on the wire, e.g. "game-status", "reserve", "practice-squad". */
export type WireCategory = string;

/** Fields every wire item carries, for ranking and filtering. */
export interface WireRanking {
  category: WireCategory;
  /** Average offense or defense snap share over his last 8 games; null without snaps */
  snapShare: number | null;
  /** snapShare of 50% or more */
  starter: boolean;
  /** Lower is bigger news: starters first, then by category */
  priority: number;
}

export interface RosterMove extends WireRanking {
  /** nflverse gsis id, matching RosterPlayer.gsisId */
  playerId: string;
  player: string;
  position: string | null;
  /** Team the move belongs to: the new team for signings and team changes */
  team: string;
  /** Previous team, for team changes only */
  fromTeam: string | null;
  type: MoveType;
  /** Involves a practice squad (these sort last) */
  practiceSquad: boolean;
  /** Plain words, e.g. "Placed on reserve list", "Joined from ATL" */
  note: string;
}

export interface InjuryEntry extends WireRanking {
  playerId: string;
  player: string;
  team: string;
  position: string | null;
  /** Game status; null until the team's last report before its game */
  status: 'Out' | 'Doubtful' | 'Questionable' | null;
  injury: string | null;
  /** "Full", "Limited", "Did not practice" */
  practice: string | null;
  /** The team's game this week is already final, so the status is history */
  gamePlayed: boolean;
}

export interface TransactionsData {
  season: number;
  /** Week the ticker shows, whose injury report this is; null in the offseason */
  week: number | null;
  /** Roster snapshot week the moves come from, and the week before it */
  movesWeek: number | null;
  comparedToWeek: number | null;
  /** ISO timestamp of the run that last changed this file */
  updated: string;
  /** Wire filter categories in priority order */
  categories: { key: WireCategory; label: string }[];
  /** Biggest news first, practice squad moves last */
  moves: RosterMove[];
  /** Out, then Doubtful, then Questionable, then practice only */
  injuries: InjuryEntry[];
}

/**
 * players/{TEAM}.json: game logs for the players currently on a team, written
 * daily by pipelines/game_logs.py. Season totals and ranks live in
 * stats/{board}.json, keyed by the same player id.
 */
export type GameLogRow = [
  week: number,
  team: string,
  opponent: string,
  home: 0 | 1,
  result: string | null,
  ...values: (number | null)[],
];

export interface PlayerLogsData {
  season: number;
  throughWeek: number;
  team: string;
  /** Names of the first five entries of every row */
  fields: ['week', 'team', 'opponent', 'home', 'result'];
  /** Per board, the column keys the rest of each row holds, in order */
  columns: Record<string, string[]>;
  /** Keyed by nflverse gsis id */
  players: Record<string, { name: string; boards: Record<string, GameLogRow[]> }>;
}

/**
 * charts/auto.json: which kept auto chart is today's. The home page shows
 * it when none of Tyler's charts is featured.
 */
export interface AutoChartData {
  /** Names charts/archive/<slug>.json, .svg and .hover.json */
  slug: string;
}

/**
 * charts/archive/<slug>.json: one auto chart, drawn by
 * pipelines/charts/auto.py beside <slug>.svg (and <slug>.hover.json).
 * Every one is kept and listed in the /charts gallery.
 */
export interface ArchivedAutoChart {
  template: 'epa' | 'wp' | 'race';
  title: string;
  note: string;
  /** What the data covers, e.g. "2026 season, through week 2" or "Sun, Sep 20" */
  asOf: string;
  source: string;
  /** YYYY-MM-DD: the game's date for win probability, else the day first drawn */
  date: string;
  /** Always starts with "Auto" */
  tags: string[];
}

/**
 * standings.json: written daily by pipelines/standings.py from completed
 * regular season games, with NFL tiebreakers (a port of nflseedR's,
 * checked against it). Before a season's first game, last season's final.
 */
export type TiebreakStep =
  | 'head_to_head'
  | 'head_to_head_sweep'
  | 'division_record'
  | 'common_games'
  | 'conference_record'
  | 'strength_of_victory'
  | 'strength_of_schedule'
  | 'division_order'
  | 'coin_toss';

export interface TeamStanding {
  team: string;
  conference: 'AFC' | 'NFC';
  division: string;
  wins: number;
  losses: number;
  ties: number;
  /** Ties count as half a win; 3 decimals */
  pct: number;
  pointsFor: number;
  pointsAgainst: number;
  diff: number;
  divisionRecord: [wins: number, losses: number, ties: number];
  conferenceRecord: [wins: number, losses: number, ties: number];
  /** "W3", "L1", "T1"; null before a first game */
  streak: string | null;
  /** 1 to 4 */
  divisionRank: number;
  /** 1 to 16: 1-4 division winners, 5-7 wild cards, then the rest */
  conferenceRank: number;
  /** The step that separated this team from teams tied with it, if any */
  divisionTiebreak: TiebreakStep | null;
  conferenceTiebreak: TiebreakStep | null;
}

export interface StandingsData {
  season: number;
  /** Last week with a completed game; 0 before any */
  throughWeek: number;
  updated: string;
  /** By conference, division, then division rank */
  teams: TeamStanding[];
}

/**
 * player_epa.json: EPA per dropback and rush EPA per carry, written weekly by
 * pipelines/player_epa.py from nflverse play-by-play (nflfastR's EPA). Every
 * qualified player, ranked; equal shown values share a rank.
 */
export interface PlayerEpaRow {
  rank: number;
  playerId: string;
  player: string;
  team: string;
  /** Per play, 3 decimals */
  value: number;
  /** Dropbacks or carries */
  plays: number;
  teamGames: number;
}

export interface PlayerEpaCategory {
  key: 'epa_per_dropback' | 'rush_epa';
  label: string;
  valueLabel: string;
  playsLabel: string;
  qualifier: { column: 'dropbacks' | 'carries'; perTeamGame: number; text: string };
  rows: PlayerEpaRow[];
}

export interface PlayerEpaData {
  season: number;
  throughWeek: number;
  updated: string;
  categories: PlayerEpaCategory[];
}

/**
 * schedule.json: every game of one season, written daily by
 * pipelines/schedule.py from the nflverse schedule. Lines appear about a
 * week before a game.
 */
export interface ScheduleGame {
  /** nflverse game id, e.g. "2026_03_SEA_WAS" */
  id: string;
  /** 1 to 18, then 19 to 22 for the playoff rounds */
  week: number;
  type: 'REG' | 'WC' | 'DIV' | 'CON' | 'SB';
  /** ISO 8601 UTC, null until scheduled */
  kickoff: string | null;
  away: string;
  home: string;
  awayScore: number | null;
  homeScore: number | null;
  overtime: boolean;
  divisional: boolean;
  neutral: boolean;
  /** Points the home team is favored by; negative when the road team is */
  spreadLine: number | null;
  /** American odds */
  awayMoneyline: number | null;
  homeMoneyline: number | null;
}

export interface ScheduleData {
  season: number;
  updated: string;
  games: ScheduleGame[];
}
