/**
 * Schemas for the JSON files in src/data/.
 *
 * These are the contract between the site and the Python pipelines: the
 * pipelines overwrite these files with real data, so mock data must match
 * these shapes exactly.
 */

/** teams.json: one entry per team, generated by pipelines/build_teams.py. */
export interface Team {
  abbr: string;
  name: string;
  /** Hex color, e.g. "#97233f" */
  primary: string;
  secondary: string;
}
export type TeamsData = Team[];

/** ticker.json: one full NFL week of games. */
export type GameState = 'pre' | 'live' | 'final';

export interface TickerGame {
  /** Stable id, e.g. "2026_02_DET_BUF" */
  id: string;
  /** Team abbr matching teams.json */
  away: string;
  home: string;
  /** null until kickoff */
  awayScore: number | null;
  homeScore: number | null;
  /**
   * Game status. The daily pipeline writes only "pre" and "final"; "live"
   * is reserved for runtime game state fetched in the browser.
   */
  state: GameState;
  /**
   * Display string: "Final", "Final/OT", "Sun 1:00 PM", "Sat TBD". Kickoff
   * times here are US Eastern; the browser replaces them with the visitor's
   * local time from `kickoff`.
   */
  detail: string;
  /** Kickoff in ISO 8601 UTC, e.g. "2026-09-18T00:15:00Z". Null until scheduled. */
  kickoff: string | null;
  /** ESPN event id recorded by nflverse, used to match live scores. Null if unknown. */
  espnId: string | null;
}

export interface TickerData {
  /** ISO timestamp of the last pipeline run */
  updated: string;
  season: number;
  /**
   * NFL week on display, chosen by pipelines/ticker.py when it runs: on
   * Tuesday the week that just ended, from Wednesday on the upcoming week.
   * Postseason weeks are 19 to 22. Null in the offseason.
   */
  week: number | null;
  /**
   * Offseason only (games empty): date of next season's opening game,
   * "YYYY-MM-DD". Null during the season.
   */
  nextOpener: string | null;
  games: TickerGame[];
}

/** leaders.json */
export interface LeaderRow {
  rank: number;
  player: string;
  /** Team abbr matching teams.json */
  team: string;
  value: number;
}

export interface LeaderCategory {
  /** Stable key, e.g. "pass_yds" */
  key: string;
  /** Display label, e.g. "Passing yards" */
  label: string;
  /** Column header for the value, e.g. "Yds" */
  valueLabel: string;
  /** Key of the full leaderboard this is the top of, e.g. "receiving" */
  board: string;
  rows: LeaderRow[];
}

export interface LeadersData {
  season: number;
  throughWeek: number;
  categories: LeaderCategory[];
}

/** on_this_day.json */
export interface OnThisDayItem {
  year: number;
  text: string;
}

export interface OnThisDayData {
  month: number;
  day: number;
  items: OnThisDayItem[];
}

/** model_record.json */
export interface ModelRecordData {
  season: number;
  /** Model's straight-up record on 4th down recommendations it graded */
  wins: number;
  losses: number;
  pushes: number;
  /** ISO timestamp of the last pipeline run */
  updated: string;
}

/** rosters/{ABBR}.json: one file per team, generated by pipelines/rosters.py. */
export type PositionGroup = 'offense' | 'defense' | 'specialists' | 'other';

export interface RosterPlayer {
  /** nflverse gsis id. Null for the occasional player without one. */
  gsisId: string | null;
  name: string;
  /**
   * URL slug, unique across the league. Players who share a name carry a
   * team suffix, so links must use this rather than deriving a slug.
   */
  slug: string;
  /** Jersey number, null when unassigned. */
  number: number | null;
  /** Specific position (CB, G, T), not the coarse group (DB, OL). */
  position: string;
  group: PositionGroup;
  /** Raw nflverse status code (ACT, RES, DEV, PUP, ...), per the nflverse roster status dictionary. */
  status: string;
  /** The code in words, e.g. "Practice squad". */
  statusLabel: string;
  /** Height in inches, null when nflverse has no listing. */
  heightInches: number | null;
  weight: number | null;
  /** Age on the day the pipeline ran. Null without a birth date. */
  age: number | null;
  /** Completed NFL seasons; 0 is a rookie. */
  experience: number;
  /** Semicolon separated when a player attended more than one. */
  college: string | null;
}

export interface TeamRoster {
  season: number;
  /** Team abbr matching teams.json */
  team: string;
  /** Week of the nflverse roster snapshot this came from. */
  week: number;
  /** ISO timestamp of the run that last changed this roster */
  updated: string;
  /** Position groups present on this roster, in display order. */
  groups: { key: PositionGroup; label: string }[];
  /** Sorted by group, then position, then jersey number. */
  players: RosterPlayer[];
}

/** team_stats.json: written weekly by pipelines/run_weekly.py from nflverse play-by-play. */
export type StatFormat = 'signed3' | 'percent1';

export interface TeamStatMetric {
  /** Stable key, e.g. "off_epa" */
  key: string;
  /** Full name, e.g. "Red zone TD rate allowed" */
  label: string;
  /** Column header, e.g. "Red zone TD" */
  short: string;
  side: 'offense' | 'defense';
  format: StatFormat;
  /** Rank 1 goes to the highest value, or the lowest for defense. */
  betterWhen: 'high' | 'low';
  /** What `n` counts: "plays", "attempts" or "trips". */
  sample: string;
  /** One sentence definition shown on the team stats page. */
  description: string;
}

export interface TeamStatValue {
  /** Rate or per play value; null when the team has no sample yet. */
  value: number | null;
  /** 1 to 32, ties shared; null when value is null. */
  rank: number | null;
  /** Plays, attempts or trips behind the value. */
  n: number;
}

export interface TeamStatLine {
  /** Team abbr matching teams.json */
  abbr: string;
  games: number;
  /** Keyed by TeamStatMetric.key */
  values: Record<string, TeamStatValue>;
}

export interface TeamStatsData {
  season: number;
  /** Last regular season week included, 0 before any games */
  throughWeek: number;
  /** ISO timestamp of the run that last changed the numbers */
  updated: string;
  metrics: TeamStatMetric[];
  teams: TeamStatLine[];
}

/** stats/{board}.json: full player leaderboards, written daily by pipelines/leaderboards.py. */
export type BoardFormat = 'integer' | 'decimal1' | 'percent1';

export interface BoardColumn {
  /** Key into BoardRow.values */
  key: string;
  /** Column header, e.g. "Y/A" */
  label: string;
  /** Full name, e.g. "Yards per carry" */
  title: string;
  format: BoardFormat;
  /** Counting stat that the per game view divides by games played. */
  perGame: boolean;
  /** A ratio of two other columns; sorting by it ranks qualified players only. */
  rate: boolean;
  /** Direction a first click sorts in, and which way rank 1 points. */
  better: 'high' | 'low';
}

export interface BoardRow {
  /** Rank by the board's primary column, totals, all players */
  rank: number;
  /** nflverse gsis id, matching RosterPlayer.gsisId */
  playerId: string;
  player: string;
  /** Team abbr matching teams.json */
  team: string;
  position: string | null;
  /** Games the player's current team has played */
  teamGames: number;
  /** Meets the board's qualifier */
  qualified: boolean;
  /** Keyed by BoardColumn.key; null where a rate has no denominator */
  values: Record<string, number | null>;
}

export interface LeaderboardData {
  /** URL key under /stats, e.g. "rushing" */
  key: string;
  label: string;
  season: number;
  throughWeek: number;
  /** Column the board ranks by by default */
  primary: string;
  qualifier: {
    /** Column the bar is measured in */
    column: string;
    perTeamGame: number;
    /** Sentence for the page, e.g. "At least 6 carries per team game." */
    text: string;
  };
  columns: BoardColumn[];
  /** Ranked by the primary column */
  rows: BoardRow[];
}
