/**
 * Schemas for the JSON files in src/data/.
 *
 * These are the contract between the site and the Python pipelines: the
 * pipelines overwrite these files with real data, so mock data must match
 * these shapes exactly.
 */

/** teams.json: one entry per team, generated by pipelines/build_teams.py. */
export interface Team {
  abbr: string;
  name: string;
  /** Hex color, e.g. "#97233f" */
  primary: string;
  secondary: string;
}
export type TeamsData = Team[];

/** ticker.json: one full NFL week of games. */
export type GameState = 'pre' | 'live' | 'final';

export interface TickerGame {
  /** Stable id, e.g. "2026_02_DET_BUF" */
  id: string;
  /** Team abbr matching teams.json */
  away: string;
  home: string;
  /** null until kickoff */
  awayScore: number | null;
  homeScore: number | null;
  /** Game status */
  state: GameState;
  /** Display string: "Final", "Sun 1:00 PM", "Q3 4:12" */
  detail: string;
}

export interface TickerData {
  /** ISO timestamp of the last pipeline run */
  updated: string;
  season: number;
  /**
   * NFL week on display, chosen by the pipeline when it runs: on Tuesday
   * the week that just ended, from Wednesday on the upcoming week.
   * Null in the offseason.
   */
  week: number | null;
  /**
   * Offseason only (games empty): date of next season's opening game,
   * "YYYY-MM-DD". Null during the season.
   */
  nextOpener: string | null;
  games: TickerGame[];
}

/** leaders.json */
export interface LeaderRow {
  rank: number;
  player: string;
  /** Team abbr matching teams.json */
  team: string;
  value: number;
}

export interface LeaderCategory {
  /** Stable key, e.g. "pass_yds" */
  key: string;
  /** Display label, e.g. "Passing yards" */
  label: string;
  /** Column header for the value, e.g. "Yds" */
  valueLabel: string;
  rows: LeaderRow[];
}

export interface LeadersData {
  season: number;
  throughWeek: number;
  categories: LeaderCategory[];
}

/** on_this_day.json */
export interface OnThisDayItem {
  year: number;
  text: string;
}

export interface OnThisDayData {
  month: number;
  day: number;
  items: OnThisDayItem[];
}

/** model_record.json */
export interface ModelRecordData {
  season: number;
  /** Model's straight-up record on 4th down recommendations it graded */
  wins: number;
  losses: number;
  pushes: number;
  /** ISO timestamp of the last pipeline run */
  updated: string;
}
